### ISSUE TITLE
Django 1.5 get_user_model() breaks aldjemy.

### ISSUE THREAD

**Issue by erikcw** [Deepwalker/aldjemy#13]
If you use Django 1.5's `get_user_model` function instead of importing the User class, aldjemy won't add the `sa` attribute to any models in that module (or modules that are setup after it).

For example:

```
# Django 1.5 style doesn't work
from django.contrib.auth import get_user_model
User = get_user_model()
```

Results in:

```
In [1]: Campaign.sa
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8cad6f5ea5c2> in <module>()
----> 1 Campaign.sa

AttributeError: type object 'Campaign' has no attribute 'sa'
```

instead of:

```
# Pre-Django 1.5 style does work.
from django.contrib.auth.models import User
```

This of course breaks Django 1.5's custom User model implementation.  This effects you even if you aren't using a custom model, since many 3rd party apps are switching to `get_user_model()` for compatibility reasons.

**Comment by Deepwalker** [comment]
Cant reproduce it. If it matters for you, please, provide broken test for test_project/sample app.
