### ISSUE TITLE
Can't disable backref generation

### ISSUE THREAD

**Issue by yuriiz** [Deepwalker/aldjemy#14]
Currently it is not possible to disable backref generation for SQLAlchemy model. It makes impossible to inherit model with two ForeignKey to same model.

Example:
```python
class A(models.Model):
    ...

class B(models.Model):
    field1 = models.ForeignKey(A, related_name='+')
    field2 = models.ForeignKey(A, related_name='+')
    class Meta:
        abstract = True

class BA(B):
    ...

class BB(B):
    ...
```
    
It is not possible to make this models work in any way and will always result in:
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Error creating backref 'ba_set' on relationship 'BA.field1': property of that name exists on mapper 'Mapper|A|app_a'

If related_name is set to '+' aldjemy shouldn't generate backref as Django does.

**Comment by blag** [comment]
@yuriiz: Can you test this patch please?

**Comment by yuriiz** [comment]
Works for me. Thanks.
