### ISSUE TITLE
Please consider adding a license file

### ISSUE THREAD

**Issue by ltalirz** [Deepwalker/aldjemy#49]
Hi, I am in the process of adding a [recipe for aldjemy](https://github.com/conda-forge/staged-recipes/pull/3212) on conda forge and I have been asked by the conda forge maintainers to raise an issue here, asking whether it would be possible to add a license file and include it in the `MANIFEST.in`?

P.S. If you would like me to add your github handle to the list of maintainers of the conda recipe (which otherwise would be just me), please let me know.

**Comment by Deepwalker** [comment]
If you can make PR with BSD license I will do it in one click ;)
