### ISSUE TITLE
UUID Primary keys

### ISSUE THREAD

**Issue by ryanhiebert** [Deepwalker/aldjemy#54]
By default, Django's models have an AutoField primary key, which is an integer. For some of my models, I have overwritten the default primary key and made it a UUIDField. I'd like to use aldjemy, but it doesn't support this case yet.

I don't know when I'll get to fixing it, though I do expect it will happen some time, but I wanted to bring it up in case there is some discussion needed to be had around it, or in case I get lucky and someone just needed to know about the problem in order to have the time to fix it sooner ;-)

**Comment by synic** [comment]
Put the following in your settings file:

```python

from sqlalchemy.types import CHAR

ALDJEMY_DATA_TYPES = {
    'UUIDField': CHAR,
}
```

**Comment by ryanhiebert** [comment]
Thanks, @synic, I'll have to try that out. I suspect that I'll want to make it a UUID specific type (for PostgreSQL in my case), but I appreciate the potential workaround using this setting.

**Comment by warrenrentlytics** [comment]
Our workaround is:

```Python
from sqlalchemy.dialects.postgresql import UUID

ALDJEMY_DATA_TYPES = {
    'UUIDField': lambda field: UUID()
}
```

**Comment by ryanhiebert** [comment]
This workaround does seem to be working. I finally got a chance to test it. Thank you.
