### ISSUE TITLE
generate tables on custom metadata

### ISSUE THREAD

**Issue by ryanhiebert** [Deepwalker/aldjemy#63]
I'm loving aldjemy, and I came up with a new interesting use case. I'm using PostgreSQL foreign data wrappers to copy loads of data from one django instance to another. To do this transfer, I need to copy between tables in different schemas. I can write these queries using SQLAlchemy, so that's what I want to do.

To that end, I want to make a custom schema, and then run `aldjemy.core.prepare_models` on it. Unfortunately, Aldjemy is pretty deeply tied to it's internal cache of the default, schema-free metadata.

I've figured out the changes needed for this, and I am using this code and it seems to be working. Since Django doesn't usually ever deal with schemas, a multiple-schema use-case, I wasn't sure if making Aldjemy internals more amenable to my use case would be something you'd be interested in having me contribute. If it would, I'd be happy to do just that. I've already got it working, I'd just need to work it into a pull request.

There are three functions that I've found need to be touched:

* `aldjemy.core.prepare_models` needs to allow passing in a custom metadata instance, and using that to do the generation.
* `aldjemy.table.generate_tables` needs to handle the case of the metadata having a schema when checking if the table exists.
*  `aldjemy.orm._extract_model_attrs` needs to support passing in a custom metadata, using that to get the tables, and use the metadata's schema when looking up the table.

All in all, pretty minor changes, but I'm not sure if cleaning things up to make that easy for me is something you think would be worthwhile to entertain a pull request for.

**Comment by Deepwalker** [comment]
Why to not just use custom sqlalchemy schema?

**Comment by ryanhiebert** [comment]
Perhaps I'm misunderstanding the question, but it sounds to me like you're asking why I don't want to manually build up a custom set of sqlalchemy tables. I don't want to do that for the same reasons that you wrote aldjemy in the first place: all the info needed for building it up is already in the django models (apart from the schema), and I don't want to repeat it.

I apologize if you were suggesting something else. If you were, could you perhaps rephrase your suggestion? There's a good chance that you know something I don't, so I'd like to understand it.

**Comment by Deepwalker** [comment]
Maybe I misunderstand your proposition – you mean you will have separate django orm schema? If this will be useful for you, then I have not any objections.

**Comment by ryanhiebert** [comment]
Sounds good, I'll open a PR so you can see what I mean in code.
