### ISSUE TITLE
"get_tables" and "get_meta" functions removed

### ISSUE THREAD

**Issue by holtgrewe** [Deepwalker/aldjemy#70]
But they are still imported in the top level module and at least `get_tables()` is referred to in the README.

**Comment by ryanhiebert** [comment]
What do you mean the "top level module"? The `__init__.py` doesn't import them, AFAICT. https://github.com/Deepwalker/aldjemy/blob/master/aldjemy/__init__.py

That said, you're right that `get_tables` still documented in the README. I did mention about that change when my PR removing it was removed, but I didn't catch that it was documented in the README at the time. I'm not sure what he would prefer as a direction, do you? I think I'd be inclined toward removing them from the docs, I'm not sure they make a ton of sense to be part of the public API.

**Comment by holtgrewe** [comment]
@ryanhiebert Yes, you were right. It is still here but could just be removed https://github.com/Deepwalker/aldjemy/blob/4c2338b32c69e9aeec8af5b4496d3f325ce02a76/aldjemy/core.py#L15

It would be nice if the documentation had an example of how to get to this information.
